### ISSUE TITLE
Code Reivew 

### ISSUE THREAD

**Issue by pshroff14** [superman-alien/project2#1]

**Comment by pshroff14** [comment]
Although, I am not well versed in HTML. I see a very organized and simplified work which eases readability.  My one stipulation is I wish there was more comments to the point where I can see what each function is specifically doing, but overall is simple and successful in utilizing the API.

**Comment by superman-alien** [comment]
Sorry about making such a misleading. I will fix that asap. Also since I
really haven't done so much about the amap of myself. Sorry about not using
google api which should be used for our class since it's not available in
china.
